version: '3'

vars:
  BINARY_NAME: macsetup

tasks:
  default:
    cmds:
      - task: build

  build:
    desc: Build the binary
    vars:
      VERSION:
        sh: git describe --tags --always --dirty 2>/dev/null || echo dev
      LDFLAGS: '-ldflags "-s -w -X main.version={{.VERSION}}"'
    cmds:
      - go build {{.LDFLAGS}} -o bin/{{.BINARY_NAME}} .
    sources:
      - ./**/*.go
    generates:
      - bin/{{.BINARY_NAME}}

  run:
    desc: Run the application
    cmds:
      - go run . -- {{.CLI_ARGS}}

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf bin/ dist/

  test:
    desc: Run tests
    cmds:
      - go test ./...

  format:
    desc: Format code with gofumpt
    cmds:
      - gofumpt -l -w .

  lint:
    desc: Run linter with golangci-lint
    deps:
      - format
    cmds:
      - golangci-lint run

  check:
    desc: Run format and lint
    deps:
      - format
      - lint

  ci:
    desc: CI checks (format check + lint + test)
    cmds:
      - |
        if [ -n "$(gofumpt -l .)" ]; then
          echo "Code is not formatted. Run 'task format' to fix."
          gofumpt -l .
          exit 1
        fi
      - golangci-lint run
      - go test ./...

  build-release:
    desc: Build release binary for Apple Silicon
    vars:
      VERSION:
        sh: git describe --tags --always --dirty 2>/dev/null || echo dev
      LDFLAGS: '-ldflags "-s -w -X main.version={{.VERSION}}"'
    cmds:
      - go build {{.LDFLAGS}} -o bin/{{.BINARY_NAME}}-darwin-arm64 .
      - echo "Built bin/{{.BINARY_NAME}}-darwin-arm64 with version {{.VERSION}}"

  release:
    desc: Create and publish a new release (usage - task release VERSION=v0.0.2)
    vars:
      VERSION: '{{.VERSION | default ""}}'
    preconditions:
      - sh: '[ -n "{{.VERSION}}" ]'
        msg: 'VERSION is required. Usage - task release VERSION=v0.0.2'
      - sh: command -v gh >/dev/null 2>&1
        msg: 'GitHub CLI (gh) is required. Install with - brew install gh'
    cmds:
      - ./scripts/release.sh {{.VERSION}}
