unbind C-a
set -g prefix C-b
set -s extended-keys on
bind C-b send-prefix

set -g default-terminal "xterm-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

set -g mouse on

set -g base-index 1
setw -g pane-base-index 1

bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# STATUS BAR  ---- start --------

# Align window names to center
set -g status-position bottom
set -g status-justify centre

# Visual identity for status + window list
set -g status-style "bg=#79b8ff,fg=black"
setw -g window-status-style "bg=#79b8ff,fg=black"
setw -g window-status-current-style "bg=black,fg=#79b8ff,bold"

setw -g window-status-bell-style "bg=red,fg=white,bold"
setw -g window-status-activity-style "bg=yellow,fg=black,bold"

set -g status-left "[#S] "
set -g status-left-length 20

set -g status-right "%Y-%m-%d %H:%M"
set -g status-right-length 30

setw -g window-status-current-format " #I:#W "
setw -g window-status-format " #I:#W "

# STATUS BAR  ---- end --------

# Use shift + left/right arrows to move across windows
bind -n S-Left  previous-window
bind -n S-Right next-window

# Use current directory names for current window name

# --- Start ----

setw -g automatic-rename off

# --- End ----


set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

run '~/.config/tmux/plugins/tpm/tpm'
